<a href="https://colab.research.google.com/github/Saurabh2997/NewPython-/blob/master/Numpy/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Numpy Basics


Write a NumPy program to test whether none of the elements of a given array is zero.

In [ ]:
a=np.array([1,2,3,45,5,6,8])
print(np.all(a))
b=np.array([0,1,2,5])
print(np.all(b))

True
False


Write a NumPy program to test whether none of the elements of a given array is zero.

In [ ]:
a=np.array([1,2,3,45,5,6,8])
np.any(a)


True

Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [ ]:
a=np.zeros(10)
print(a)
b=np.ones(10)
print(b)
c=np.ones(10)*5
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


Write a NumPy program to create an array of the integers from 30 to70.

In [ ]:
a=np.arange(30,70)
print(a)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


Write a NumPy program to create an array of all the even integers from 30 to 70

In [ ]:
a=np.arange(30,70,2)
print(a)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


Write a NumPy program to create a 3x3 identity matrix.

In [ ]:
a=np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Write a NumPy program to generate a random number between 0 and 1

In [ ]:
a=np.random.normal(0,1,size=1)
print(a)

[0.01007414]


Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution

In [ ]:
a=np.random.standard_normal(15)
print(a)

[-1.87670541  0.54528657 -0.32235641 -0.59444143  1.58062783 -0.81311807
 -2.5832603   1.17823293 -0.53901245 -0.03003852  1.73807667 -0.46028948
  0.91880908  0.29724772  0.80671854]


Write a NumPy program to create a 3X4 array using and iterate over it.

In [ ]:
a=np.random.randint(1,50,(3,4))
print(a)

[[24  1 26 17]
 [16 31  5 11]
 [23 32 37 37]]


In [ ]:

a = np.arange(10,22).reshape((3, 4))
print("Original array:")
print(a)
print("Each element of the array is:")
for x in np.nditer(a):
  print(x,end=" ")

Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 

Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50

In [ ]:
a=np.linspace(5,50,10)
print(a)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15

In [ ]:
a=np.arange(20)
print('Original array',a)
a[(a>=9)&(a<=15)]*=-1
print(a)

Original array [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19]


. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.

In [ ]:
a=np.random.randint(0,10,5)
print(a)

[2 9 6 4 7]


Write a NumPy program to multiply the values of two given vectors

In [ ]:
a=np.arange(5)
b=np.ones(5)*2
print('array 1',a)
print('array 2',b)
c=a*b
print('array 1*2',c)

array 1 [0 1 2 3 4]
array 2 [2. 2. 2. 2. 2.]
array 1*2 [0. 2. 4. 6. 8.]


Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21

In [ ]:
a=np.random.randint(10,21,(3,4))
print(a)

[[14 15 17 11]
 [14 18 11 18]
 [19 19 16 10]]


Write a NumPy program to find the number of rows and columns of a given matrix.

In [ ]:
a = np.random.randint(0,22,(3,4))
print(a)
print(np.shape(a))

[[18 19  2 13]
 [ 4  1  2  3]
 [ 5  8  3  3]]
(3, 4)


Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0

In [ ]:
a=np.ones((10,10))
a[1:-1,1:-1]=0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [ ]:
a=np.identity(5)
b=[1,2,3,4,5]
c=a*b
print(c)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


In [ ]:
x = np.diag([1, 2, 3, 4, 5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


 Write a NumPy program to create a 3x3x3 array filled with arbitrary values

In [ ]:
a=np.random.randint(0,50,(3,3,3,))
print(a)

[[[ 7  3 27]
  [31 39 30]
  [33 39 19]]

 [[20 46 16]
  [40 46 24]
  [29  4 18]]

 [[29 13  0]
  [39  3  3]
  [16  0 15]]]


Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.

In [ ]:
a=np.random.randint(0,50,(3,3))
print(a)
print('sum of row',a.sum(1))
print('sum of column',a.sum(0))

[[ 0 47 36]
 [20 35 15]
 [46 39 11]]
sum of row [83 70 96]
sum of column [ 66 121  62]


Write a NumPy program to add a vector to each row of a given matrix

In [ ]:
a=np.random.randint(2,50,(3,3))
print(a)
b=[1,1,1]
c=a+b
print(c)

[[ 7 11 13]
 [40 21 29]
 [ 8 48  9]]
[[ 8 12 14]
 [41 22 30]
 [ 9 49 10]]


In [ ]:
m = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 1, 0])
print("Original vector:")
print(v)
print("Original matrix:")
print(m)
result = np.empty_like(m) 
for i in range(4):
  result[i, :] = m[i, :] + v
print("\nAfter adding the vector v to each row of the matrix m:")
print(result)

Original vector:
[1 1 0]
Original matrix:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

After adding the vector v to each row of the matrix m:
[[ 2  3  3]
 [ 5  6  6]
 [ 8  9  9]
 [11 12 12]]


# NumPy: Sorting and Searching Exercises, Practice, Solution

Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array

In [ ]:
a=np.array([[10,40],[30,20]])
print(a)
print('Sorted on first axis')
print(np.sort(a,0))
print("Sort the array along the last axis:")
print(np.sort(a))
print("Sort the flattened array:")
print(np.sort(a, axis=None))

[[10 40]
 [30 20]]
Sorted on first axis
[[10 20]
 [30 40]]
Sort the array along the last axis:
[[10 40]
 [20 30]]
Sort the flattened array:
[10 20 30 40]


. Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort the array on height

In [ ]:
data=[('name','S15'),('class',int),('height',float)]
students_details = [('James', 5, 48.5), ('Nail', 6, 52.5),('Paul', 5, 42.10), ('Pit', 5, 40.11)]
a=np.array(students_details,dtype=data)
print('original array')
print(a)
print('After sort')
k=np.sort(a,order='height')
print(k)

original array
[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )
 (b'Pit', 5, 40.11)]
After sort
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 )]


Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort by class, then height if class are equal

In [ ]:
data=[('name','S15'),('class',int),('height',float)]
students_details = [('James', 5, 48.5), ('Nail', 6, 52.5),('Paul', 5, 42.10), ('Pit', 5, 40.11)]
a=np.array(students_details,dtype=data)
print('original array')
print(a)
print('After sort')
k=np.sort(a,order=['class','height'])
print(k)

original array
[(b'James', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul', 5, 42.1 )
 (b'Pit', 5, 40.11)]
After sort
[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 )]


Write a NumPy program to sort the student id with increasing height of the students from given students id and height. Print the integer indices that describes the sort order by multiple columns and the sorted data.

In [ ]:
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
student_height = np.array([40., 42., 45., 41., 38., 40., 42.0])
#Sort by studen_id then by student_height
indices = np.lexsort((student_id, student_height))
print("Sorted indices:")
print(indices)
print("Sorted data:")
for n in indices:
  print(student_id[n], student_height[n])

Sorted indices:
[4 0 5 3 6 1 2]
Sorted data:
1682 38.0
1023 40.0
5241 40.0
1671 41.0
4532 42.0
5202 42.0
6230 45.0


Write a NumPy program to get the indices of the sorted elements of a given array.

In [ ]:
l=[1023 ,5202 ,6230 ,1671 ,1682 ,5241 ,4532]
a=np.array(l)
print('Original array',a)
k=np.argsort(a)
print('Sorted indices',k)
print('Sorted array',a[k])

Original array [1023 5202 6230 1671 1682 5241 4532]
Sorted indices [0 3 4 6 1 5 2]
Sorted array [1023 1671 1682 4532 5202 5241 6230]


Write a NumPy program to partition a given array in a specified position and move all the smaller elements values to the left of the partition, and the remaining values to the right, in arbitrary order (based on random choice)

In [ ]:
nums = np.array([70, 50, 20, 30, -11, 60, 50, 40])
print("Original array:")
print(nums)
print("\nAfter partitioning on 4 the position:")
print(np.partition(nums, 4))

Original array:
[ 70  50  20  30 -11  60  50  40]

After partitioning on 4 the position:
[-11  30  20  40  50  50  60  70]


Write a NumPy program to sort the specified number of elements from beginning of a given array

In [ ]:
a=np.random.randint(0,20,10)
print(a[np.argpartition(a,range(5))])

[ 1  2  4  6 11 15 18 11 18 12]


# NumPy: Array Object Exercises, Practice, Solution

Write a NumPy program to create a null vector of size 10 and update sixth value to 11

In [ ]:
a=np.zeros(10)
print('Og vector',a)
a[5]=11
print('new vector',a)

Og vector [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
new vector [ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


Write a NumPy program to create an array with values ranging from 12 to 38

In [ ]:
a=np.arange(12,39)
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


Write a NumPy program to reverse an array (first element becomes last).

In [ ]:
a=np.arange(12,38)
a[-1::-1]

array([37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21,
       20, 19, 18, 17, 16, 15, 14, 13, 12])

Write a NumPy program to convert an array to a float type

In [ ]:
a=np.array([1,2,3,4])
print(a)
a=np.array(a,dtype=float)
print(a)

[1 2 3 4]
[1. 2. 3. 4.]


Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [ ]:
a=np.zeros((8,8))
a[1::2,::2]=1
a[::2,1::2]=1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Write a NumPy program to append values to the end of an array.

In [ ]:
a=np.arange(5)
print(a)
b=np.array([5,7,9,2])
np.append(a,b)

[0 1 2 3 4]


array([0, 1, 2, 3, 4, 5, 7, 9, 2])

Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. 

In [ ]:
a=np.random.random_sample(8)
print(len(a))
print(a.size,a.nbytes,a.itemsize)


8
8 64 8


Write a NumPy program to test whether each element of a 1-D array is also present in a second array.

In [ ]:
a=np.array([10,20,40,50])
b=np.array([10,5,40,60])
np.in1d(a,b)

array([ True, False,  True, False])

Write a NumPy program to find common values between two arrays.

In [ ]:
a=np.array([10,20,30,80])
b=np.array([10,50,30,90])
k=a[np.isin(a,b)]
print(k)

[10 30]


In [ ]:
a=np.array([10,20,30,80])
b=np.array([10,50,30,90])
np.intersect1d(a,b)


array([10, 30])

Write a NumPy program to get the unique elements of an array

In [ ]:
a=np.array([10,20,20,50,50,80,50,90,100,10,100,60])
np.unique(a)

array([ 10,  20,  50,  60,  80,  90, 100])

 Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.

In [ ]:
a=np.array([10,20,50,100,10,90,60])
b=np.array([50,20,100,30,80,90,100,140])
np.setdiff1d(a,b)


array([10, 60])

 Write a NumPy program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays

In [7]:
a=np.array([10,20,50,100,10,90,60])
b=np.array([50,20,100,30,80,90,100,140])
np.setxor1d(a,b)

array([ 10,  30,  60,  80, 140])

 Write a NumPy program to find the union of two arrays. Union will return the unique, sorted array of values that are in either of the two input arrays

In [10]:
a=np.array([10,20,50,100,10,90,60])
b=np.array([50,20,100,30,80,90,100,140])
np.union1d(a,b)

array([ 10,  20,  30,  50,  60,  80,  90, 100, 140])

Write a NumPy program to test whether all elements in an array evaluate to True

In [21]:
b=np.array([50,0,100,0,80,90,100,140,0])
np.all(b)

False

Write a NumPy program to test whether any array element along a given axis evaluates to

In [22]:
a=np.random.randint(0,10,(3,3))
print(a)
np.all(a,axis=0)

[[0 9 8]
 [2 2 8]
 [1 0 5]]


array([False, False,  True])

Write a NumPy program to construct an array by repeating

In [26]:
a=np.array([1,2,3,4])
print('Repeated Elements')
np.tile(a,2)

Repeated Elements


array([1, 2, 3, 4, 1, 2, 3, 4])

Write a NumPy program to repeat elements of an array. 

In [28]:
a=np.array([1,2,3,4])
print('Repeat Each Elements')
np.repeat(a,2)

Repeat Each Elements


array([1, 1, 2, 2, 3, 3, 4, 4])

In [9]:
import re
test_data = ["1912", "1929", "1913-1923",
             "(1951)", "1994", "1934",
             "c. 1915", "1995", "c. 1912",
             "(1988)", "2002", "1957-1959",
             "c. 1955.", "c. 1970's", 
             "C. 1990-1999"]

bad_chars = ["(",")","c","C",".","s","'", " "]

a=re.compile('[(,),c,C,.,\',s,\s]')
for i in test_data:

    k=re.sub(a,"",i)
    print(k)






1912
1929
1913-1923
1951
1994
1934
1915
1995
1912
1988
2002
1957-1959
1955
1970
1990-1999
